events {}

http {
    upstream article_services {
        server article-service:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://article_services;
        }
    }
}
